{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "\n",
      "\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023560DF9390>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C9E8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "early stopping after 1000 iterations without improvements with 1025 steps: best metric value 352193.09375\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_000\\graph\\data_augmentation_adadelta_000\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_000\\graph\\data_augmentation_adadelta_000\n",
      "TRAIN mean log loss: 0.4831665652838341\n",
      "TRAIN mean AUC: 0.5423072092789748\n",
      "VALID mean log loss: 0.4833032617066393\n",
      "VALID mean AUC: 0.532325761994095\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_000\\graph\\data_augmentation_adadelta_000\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_000\\graph\\data_augmentation_adadelta_000\n",
      "Experiment 0 with 81 genes and 4 clinical markers\n",
      "Train: 0.554171371354311\n",
      "Valid: 0.45828838547285145\n",
      "\n",
      "========================================================================================\n",
      "\n",
      "1\n",
      "\n",
      "\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833278>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833278>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000023558319D30>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833DA0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833DA0>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833DA0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C833DA0>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355CA0D358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355CA0D358>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355CA0D358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355CA0D358>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C830470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C830470>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C830470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C830470>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "early stopping after 1000 iterations without improvements with 1141 steps: best metric value 17032.591796875\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_001\\graph\\data_augmentation_adadelta_001\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_001\\graph\\data_augmentation_adadelta_001\n",
      "TRAIN mean log loss: 0.4813989575889055\n",
      "TRAIN mean AUC: 0.5698655416939612\n",
      "VALID mean log loss: 0.4833285560404537\n",
      "VALID mean AUC: 0.49501548296462444\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_001\\graph\\data_augmentation_adadelta_001\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_001\\graph\\data_augmentation_adadelta_001\n",
      "Experiment 1 with 51 genes and 4 clinical markers\n",
      "Train: 0.5607019636908372\n",
      "Valid: 0.519484897518878\n",
      "\n",
      "========================================================================================\n",
      "\n",
      "2\n",
      "\n",
      "\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235560F1128>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000235561F9B38>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "early stopping after 1000 iterations without improvements with 2138 steps: best metric value 113252.5\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_002\\graph\\data_augmentation_adadelta_002\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_002\\graph\\data_augmentation_adadelta_002\n",
      "TRAIN mean log loss: 0.47960395292296326\n",
      "TRAIN mean AUC: 0.5939290452405397\n",
      "VALID mean log loss: 0.48285456929922393\n",
      "VALID mean AUC: 0.5087460067066675\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_002\\graph\\data_augmentation_adadelta_002\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_002\\graph\\data_augmentation_adadelta_002\n",
      "Experiment 2 with 71 genes and 4 clinical markers\n",
      "Train: 0.5934533173514113\n",
      "Valid: 0.471458108594031\n",
      "\n",
      "========================================================================================\n",
      "\n",
      "3\n",
      "\n",
      "\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99CD68>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C860>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C470>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002355C99C470>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "early stopping after 1000 iterations without improvements with 2066 steps: best metric value 155801.796875\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_003\\graph\\data_augmentation_adadelta_003\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_003\\graph\\data_augmentation_adadelta_003\n",
      "TRAIN mean log loss: 0.4798725169009486\n",
      "TRAIN mean AUC: 0.6086005939276967\n",
      "VALID mean log loss: 0.48297390144435265\n",
      "VALID mean AUC: 0.5132512125252834\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_003\\graph\\data_augmentation_adadelta_003\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\Venezian\\git\\multiple-myeloma\\experiments\\exp-geo\\output\\mult\\dae\\data_augmentation_adadelta_003\\graph\\data_augmentation_adadelta_003\n",
      "Experiment 3 with 73 genes and 4 clinical markers\n",
      "Train: 0.6140980482815631\n",
      "Valid: 0.5166396103896104\n",
      "\n",
      "========================================================================================\n",
      "\n",
      "4\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.insert(0, '../../')\n",
    "\n",
    "from data import load_data_gse135820 as gse135820, load_data_gse68465 as gse68465\n",
    "from data import load_data_gse94873 as gse94873, load_data_gse96058 as gse96058\n",
    "\n",
    "from pipeline import MuLT\n",
    "\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from evaluation import optimize_threshold, classification_metrics\n",
    "from sklearn.metrics import roc_auc_score, log_loss, confusion_matrix\n",
    "\n",
    "\n",
    "from constants import N_FOLDS, RANDOM_STATE\n",
    "from util import join_values\n",
    "\n",
    "import lightgbm as lgb\n",
    "import pickle as pkl\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import time\n",
    "import os\n",
    "\n",
    "# creating analyser object to compute and group \n",
    "# classification matrics grouped by training and validation\n",
    "# dataset and by experiment id\n",
    "# analyser = Analyser()\n",
    "\n",
    "dataset_id = ['GSE135820', 'GSE68465', 'GSE94873', 'GSE96058']\n",
    "\n",
    "for i, func in enumerate([gse135820, gse68465, gse94873, gse96058]):\n",
    "    \n",
    "    c, g, o = func()\n",
    "\n",
    "    # Creating 10-fold CV splits stratified by treatments and outcome\n",
    "    kfold = StratifiedKFold(N_FOLDS, shuffle=True, random_state=RANDOM_STATE)\n",
    "    split = kfold.split(np.zeros(o.shape[0]), o)\n",
    "\n",
    "    #\n",
    "    #\n",
    "    result = {c: [] for c in ['dataset', 'experiment', 'train_auc', 'valid_auc', \n",
    "                              'train_loss', 'valid_loss', 'execution_time', 'threshold']}\n",
    "\n",
    "    for experiment, (train_index, valid_index) in enumerate(split):\n",
    "\n",
    "        initial_time = time.time()\n",
    "\n",
    "        print('{}\\n\\n'.format(experiment))\n",
    "\n",
    "        #######################################################################################################\n",
    "        # Split train & valid\n",
    "        #######################################################################################################\n",
    "\n",
    "        response_train = o.iloc[train_index, 0]\n",
    "        response_valid = o.iloc[valid_index, 0]\n",
    "\n",
    "        clinical_train = c.iloc[train_index, :]\n",
    "        clinical_valid = c.iloc[valid_index, :]\n",
    "\n",
    "        # treatments_train = treatments.iloc[train_index, :]\n",
    "        # treatments_valid = treatments.iloc[valid_index, :]\n",
    "\n",
    "        genes_train = g.iloc[train_index, :]\n",
    "        genes_valid = g.iloc[valid_index, :]\n",
    "\n",
    "        #######################################################################################################\n",
    "        # MuLT fitting\n",
    "        #######################################################################################################\n",
    "\n",
    "        mult = MuLT(experiment_number=experiment, \n",
    "                    number_of_experiments=N_FOLDS, \n",
    "                    output_path='./output/mult/', \n",
    "                    random_state=RANDOM_STATE)\n",
    "\n",
    "        mult.fit(clinical=clinical_train, genes=genes_train, outcome=response_train, \n",
    "\n",
    "            lgb_fixed_parameters = {\n",
    "                'metric': 'binary_logloss',\n",
    "                'n_estimators': 100,\n",
    "                'objective': 'binary',\n",
    "                'is_unbalance': False, \n",
    "                'extra_trees': True,\n",
    "                'max_depth': 4,\n",
    "                'learning_rate': 0.1,\n",
    "                'min_split_gain': 0.0001,\n",
    "                'min_child_weight': 0.0001},\n",
    "\n",
    "            optimization_n_call=25,\n",
    "            optimization_n_folds=2,\n",
    "            optimization_early_stopping_rounds=1,\n",
    "\n",
    "            clinical_marker_selection_threshold=0.05,\n",
    "            gene_selection_threshold=0.05,\n",
    "\n",
    "            dae_decay_rate=1.0,\n",
    "            dae_learning_rate=1e-3,\n",
    "            dae_steps=100000,\n",
    "            dae_early_stopping_rounds=1000,\n",
    "\n",
    "            lgb_early_stopping_rounds=1,\n",
    "\n",
    "            predictor_n_folds=3)\n",
    "\n",
    "        with open('output/mult/trained_model_{}.pkl'.format(experiment), 'wb') as file:\n",
    "            pkl.dump(mult, file)\n",
    "\n",
    "        #######################################################################################################\n",
    "        # MuLT inference\n",
    "        #######################################################################################################\n",
    "\n",
    "        y_hat_train = mult.predict(clinical=clinical_train, genes=genes_train)\n",
    "        y_hat_valid = mult.predict(clinical=clinical_valid, genes=genes_valid)\n",
    "\n",
    "        #################################################################################################\n",
    "        # Analysing Performance\n",
    "        #################################################################################################   \n",
    "\n",
    "        # Computing AUC\n",
    "        train_auc = roc_auc_score(response_train, y_hat_train)\n",
    "        valid_auc = roc_auc_score(response_valid, y_hat_valid)\n",
    "\n",
    "        # Computing logLoss\n",
    "        train_loss = log_loss(response_train, y_hat_train)\n",
    "        valid_loss = log_loss(response_valid, y_hat_valid)\n",
    "\n",
    "        # Compute optimized threshold\n",
    "        opt_threshold = optimize_threshold(response_train, y_hat_train)\n",
    "\n",
    "        if opt_threshold is None:\n",
    "            opt_threshold = np.mean(response_train)\n",
    "\n",
    "        # compute confusion matrix\n",
    "        tn, fp, fn, tp = confusion_matrix(response_valid, [int(y >= opt_threshold) for y in y_hat_valid]).ravel()\n",
    "\n",
    "        classification_results = classification_metrics(tn, fp, fn, tp)\n",
    "\n",
    "        # add results to data frame (dict for now)\n",
    "        for k in classification_results:\n",
    "            if k not in result:\n",
    "                result[k] = []\n",
    "            result[k].append(classification_results[k])\n",
    "\n",
    "        result['experiment'].append(experiment)\n",
    "        result['train_auc'].append(train_auc)\n",
    "        result['valid_auc'].append(valid_auc)\n",
    "        result['train_loss'].append(train_loss)\n",
    "        result['valid_loss'].append(valid_loss)\n",
    "        result['execution_time'].append(time.time() - initial_time)\n",
    "        result['threshold'].append(opt_threshold)\n",
    "        result['dataset'].append(dataset_id[i])\n",
    "        \n",
    "        print('Experiment {} with {} genes and {} clinical markers'.format(\n",
    "              experiment, len(mult.selected_genes[0]), len(mult.selected_clinical[0])))\n",
    "\n",
    "        print('Train: {}'.format(train_auc))\n",
    "\n",
    "        print('Valid: {}'.format(valid_auc))\n",
    "\n",
    "        print(\"\\n========================================================================================\\n\")\n",
    "        \n",
    "        # Exporting inference\n",
    "        response_train = pd.DataFrame(response_train)\n",
    "        response_train['y_hat'] = y_hat_train\n",
    "        response_train.to_csv('output/mult/inference/train_{}.csv'.format(experiment), index=True, sep=',')\n",
    "\n",
    "        response_valid = pd.DataFrame(response_valid)\n",
    "        response_valid['y_hat'] = y_hat_valid\n",
    "        response_valid.to_csv('output/mult/inference/valid_{}.csv'.format(experiment), index=True, sep=',')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "g.sample(n=600, random_state=10) * 100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "o.sum()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
